services:
  ################## Portainer (container management) ################## 
  portainer:
    image: portainer/portainer-ce:2.21.3
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`portainer.isaac-software.engineer`)"
      - "traefik.http.routers.portainer.tls=false"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  portainer-data:
    driver: local
